version: "3.9"
services:
  am_elasticsearch:
    container_name: am_elasticsearch 
    image: elasticsearch:8.4.1
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_PASSWORD=123
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  am_service:
    container_name: am_service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:5120
    working_dir: /src/
    entrypoint: /usr/bin/dotnet run --launch-profile AdvMusicTestProduction 
  am_hangfire:
    container_name: am_hangfire
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    working_dir: /src/
    entrypoint: /usr/bin/dotnet run --launch-profile AdvMusicTest_HangfireProduction